### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by dcryptoniun** [dcryptoniun/base-react-tailwind-dark#1]
The current README file needs to be updated to provide clearer and more up-to-date information about the project. The current file lacks important details, such as instructions on how to install and run the project, and the latest changes made to the codebase.

To improve the project's documentation and make it more user-friendly for potential contributors and users, we need to update the README file. The updated file should include the following information:

Project description and goals
Instructions on how to install and run the project
Information about the latest changes made to the codebase
Contribution guidelines for potential contributors
Contact information for the project maintainers
By updating the README file, we can ensure that potential contributors and users have a clear understanding of the project and how to use it, which will ultimately improve the project's success and sustainability.

**Comment by hakrsh** [comment]
I have created a new readme with the details.
