### ISSUE TITLE
Need to Fix dark mode state on reload

### ISSUE THREAD

**Issue by dcryptoniun** [dcryptoniun/base-react-tailwind-dark#3]
When the user reloads the website, the theme return to the default state.

Additional Information
This change should be tested thoroughly to ensure it does not cause unintended consequences.

**Comment by pravinargade18** [comment]
Hey @dcryptoniun! I want to work on this issue. Can you assign it to me, please?

**Comment by dcryptoniun** [comment]
@pravinargade18 sure
